name: CICD

on: [push]

env:
  APPLICATION_NAME: tk8web
  REPO_NAME: kubernauts
  KUBE_CONFIG: "${{ secrets.KUBECONFIG }}"

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Push image
      run: |
        echo $KUBE_CONFIG | base64 -d | tee $HOME/kconfig
        kubectl cluster-info --kubeconfig="$HOME/kconfig"
           

          
