name: CICD

on: [push]

env:
  APPLICATION_NAME: tk8web
  REPO_NAME: kubernauts
  KUBE_CONFIG: "${{ secrets.KUBECONFIG }}"

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo $KUBE_CONFIG | base64 -d > ~/.kube/config
        
    - name: run kubectl
      run: |
        kubectl cluster-info 

    - name: cleanup kubeconfig
      run: |
        rm -f ~/.kube/config
          
