name: CICD

on: [push]

env:
  APPLICATION_NAME: tk8web
  REPO_NAME: kubernauts
  KUBECONFIG: "${{ secrets.KUBECONFIG }}"

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: setup kubectl
      run: |
          kubectl cluster-info
          
